-- ============================================================
-- execution_nodes — model-aligned DDL, smm schema, and operational queries
-- Dialect: PostgreSQL 14+
-- ============================================================
-- Supersedes section 3 of docs/sql/smm_gtm_bridge.sql, which was written
-- before backend/app/models/execution_node.py existed and drifted from it
-- in seven concrete ways (see "DRIFT FROM smm_gtm_bridge.sql" at the end).
--
-- SOURCE OF TRUTH IS THE ORM MODEL, NOT THIS FILE.
-- The table itself must be created by Alembic:
--     cd backend && alembic revision --autogenerate -m "add execution_nodes"
-- Section 1 below is the shape that autogenerate is expected to emit; use it
-- to verify the generated migration, not as a substitute for running it.
-- Sections 2-4 are the parts autogenerate will NOT produce (the smm schema,
-- its functions, and the read-model queries) and are applied separately.
-- ============================================================


-- ============================================================
-- 0. Schema
-- ============================================================
-- smm_gtm_bridge.sql defines smm.* functions and views but never creates the
-- schema, so every CREATE FUNCTION in it fails on a clean database.
CREATE SCHEMA IF NOT EXISTS smm;


-- ============================================================
-- 1. Table (verification target for the Alembic autogenerate output)
-- ============================================================

-- Enum labels are the Python member NAMES, uppercase — not the .value
-- strings. SQLAlchemy's Enum() persists .name unless values_callable is
-- passed, and nothing in backend/app/ passes it. Confirmed against
-- 92ba5d1cd517_initial_schema.py, where every existing enum
-- (post_status, campaign_status, approval_status, ...) is uppercase.
CREATE TYPE workflow_node_type AS ENUM (
    'INTAKE', 'CAMPAIGN', 'POST', 'PUBLISH_JOB', 'APPROVAL', 'INTEGRATION_EVENT'
);

CREATE TYPE workflow_node_status AS ENUM (
    'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'
);

CREATE TYPE execution_node_ref_type AS ENUM (
    'CAMPAIGN', 'POST', 'SCHEDULE', 'PUBLISH_JOB', 'APPROVAL', 'AUDIT_LOG'
);

CREATE TABLE execution_nodes (
    -- No gen_random_uuid() server default: UUIDPkMixin generates ids
    -- application-side on purpose, so the same model runs on the SQLite
    -- test suite. See the design note at the top of app/models/base.py.
    id                   uuid         NOT NULL,
    organization_id      uuid         NOT NULL,
    workflow_instance_id uuid         NOT NULL,
    parent_node_id       uuid         NULL,
    node_type            workflow_node_type   NOT NULL,
    status               workflow_node_status NOT NULL,
    display_name         varchar(255) NULL,
    ref_id               uuid         NULL,
    ref_type             execution_node_ref_type NULL,
    failure_reason       varchar(1000) NULL,
    completed_at         timestamptz  NULL,
    -- TimestampMixin: both columns are NOT NULL with no server default, so
    -- every raw-SQL INSERT must supply them explicitly.
    created_at           timestamptz  NOT NULL,
    updated_at           timestamptz  NOT NULL,

    CONSTRAINT pk_execution_nodes PRIMARY KEY (id),
    CONSTRAINT fk_execution_nodes_organization_id
        FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_execution_nodes_parent_node_id
        FOREIGN KEY (parent_node_id) REFERENCES execution_nodes (id) ON DELETE SET NULL
);

-- These five mirror index=True on the model; the names are what SQLAlchemy's
-- default naming convention produces, so autogenerate will match them.
CREATE INDEX ix_execution_nodes_organization_id      ON execution_nodes (organization_id);
CREATE INDEX ix_execution_nodes_workflow_instance_id ON execution_nodes (workflow_instance_id);
CREATE INDEX ix_execution_nodes_parent_node_id       ON execution_nodes (parent_node_id);
CREATE INDEX ix_execution_nodes_node_type            ON execution_nodes (node_type);
CREATE INDEX ix_execution_nodes_status               ON execution_nodes (status);
CREATE INDEX ix_execution_nodes_ref_id               ON execution_nodes (ref_id);
CREATE INDEX ix_execution_nodes_ref_type             ON execution_nodes (ref_type);

-- Hot-path composites. Not emitted by autogenerate — add them to the
-- migration by hand, after the autogenerated block.
--
-- Resolving (workflow_instance_id, ref_id, ref_type) -> node is the lookup
-- every status-completion write does; org first keeps it tenant-scoped.
CREATE INDEX ix_execution_nodes_org_workflow_ref
    ON execution_nodes (organization_id, workflow_instance_id, ref_type, ref_id);

-- Backs the "what is still in flight" operational query in section 4a.
CREATE INDEX ix_execution_nodes_org_open
    ON execution_nodes (organization_id, created_at DESC)
    WHERE status IN ('PENDING', 'RUNNING');


-- ============================================================
-- 2. smm helper functions
-- ============================================================
-- The ORM path (app/services/workflow_service.py) is the primary writer and
-- already covers create/append/update. These exist for the SQL bridge and
-- for out-of-band recovery — they must produce rows indistinguishable from
-- what the ORM writes, which is why each one sets id/created_at/updated_at.

-- 2a. Bootstrap a workflow instance and return its root node id.
--
-- Signature change from smm_gtm_bridge.sql 3a: that version returned the
-- generated workflow_instance_id and discarded the root node's id, so a
-- caller had no handle to pass as parent_node_id when appending children.
-- This returns both. It also takes workflow_instance_id as an argument
-- rather than generating it, matching WorkflowService.create_workflow_instance,
-- which requires the caller to supply it.
CREATE OR REPLACE FUNCTION smm.create_workflow_instance(
    p_organization_id      uuid,
    p_workflow_instance_id uuid,
    p_root_ref_id          uuid,
    p_root_ref_type        execution_node_ref_type,
    p_node_type            workflow_node_type DEFAULT 'CAMPAIGN',
    p_display_name         varchar(255) DEFAULT NULL
)
RETURNS TABLE (root_node_id uuid, workflow_instance_id uuid)
LANGUAGE plpgsql AS $$
DECLARE
    v_root_id uuid := gen_random_uuid();
    v_now     timestamptz := now();
BEGIN
    INSERT INTO execution_nodes (
        id, organization_id, workflow_instance_id, parent_node_id,
        node_type, status, display_name, ref_id, ref_type,
        created_at, updated_at
    )
    VALUES (
        v_root_id, p_organization_id, p_workflow_instance_id, NULL,
        p_node_type, 'SUCCEEDED',
        COALESCE(p_display_name, 'workflow-' || left(replace(p_workflow_instance_id::text, '-', ''), 8)),
        p_root_ref_id, p_root_ref_type,
        v_now, v_now
    );

    RETURN QUERY SELECT v_root_id, p_workflow_instance_id;
END;
$$;

-- Usage:
--   SELECT * FROM smm.create_workflow_instance(
--       :organization_id, :workflow_instance_id, :campaign_id, 'CAMPAIGN');


-- 2b. Append child nodes for every approval and publish job on a post.
--
-- Replaces the two bare INSERT statements in smm_gtm_bridge.sql 3b, which
-- were not idempotent: re-running the bridge for the same post duplicated
-- every child node. The NOT EXISTS guard makes re-ingestion safe.
CREATE OR REPLACE FUNCTION smm.append_post_child_nodes(
    p_organization_id      uuid,
    p_workflow_instance_id uuid,
    p_parent_node_id       uuid,
    p_post_id              uuid
)
RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    v_now      timestamptz := now();
    v_inserted integer;
    v_total    integer := 0;
BEGIN
    INSERT INTO execution_nodes (
        id, organization_id, workflow_instance_id, parent_node_id,
        node_type, status, display_name, ref_id, ref_type,
        created_at, updated_at
    )
    SELECT
        gen_random_uuid(), p_organization_id, p_workflow_instance_id, p_parent_node_id,
        'APPROVAL', 'PENDING', 'approval:' || a.stage, a.id, 'APPROVAL',
        v_now, v_now
    FROM approvals a
    WHERE a.post_id = p_post_id
      AND a.organization_id = p_organization_id
      AND NOT EXISTS (
          SELECT 1 FROM execution_nodes n
          WHERE n.organization_id      = p_organization_id
            AND n.workflow_instance_id = p_workflow_instance_id
            AND n.ref_type             = 'APPROVAL'
            AND n.ref_id               = a.id
      );
    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    v_total := v_total + v_inserted;

    INSERT INTO execution_nodes (
        id, organization_id, workflow_instance_id, parent_node_id,
        node_type, status, display_name, ref_id, ref_type,
        created_at, updated_at
    )
    SELECT
        gen_random_uuid(), p_organization_id, p_workflow_instance_id, p_parent_node_id,
        'PUBLISH_JOB', 'PENDING', 'publish:' || j.id::text, j.id, 'PUBLISH_JOB',
        v_now, v_now
    FROM publish_jobs j
    WHERE j.post_id = p_post_id
      AND j.organization_id = p_organization_id
      AND NOT EXISTS (
          SELECT 1 FROM execution_nodes n
          WHERE n.organization_id      = p_organization_id
            AND n.workflow_instance_id = p_workflow_instance_id
            AND n.ref_type             = 'PUBLISH_JOB'
            AND n.ref_id               = j.id
      );
    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    v_total := v_total + v_inserted;

    RETURN v_total;
END;
$$;


-- 2c. Complete or fail a node by its (workflow, ref) coordinates.
--
-- smm_gtm_bridge.sql 3c did this as two loose UPDATEs with no
-- organization_id predicate — a cross-tenant write if two orgs ever collide
-- on a ref_id. Tenant scoping is mandatory here per the repository-layer
-- defense-in-depth rule.
CREATE OR REPLACE FUNCTION smm.complete_execution_node(
    p_organization_id      uuid,
    p_workflow_instance_id uuid,
    p_ref_id               uuid,
    p_ref_type             execution_node_ref_type,
    p_status               workflow_node_status,
    p_failure_reason       varchar(1000) DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE
    v_updated integer;
BEGIN
    IF p_status NOT IN ('SUCCEEDED', 'FAILED', 'CANCELLED') THEN
        RAISE EXCEPTION 'complete_execution_node expects a terminal status, got %', p_status;
    END IF;

    IF p_status = 'FAILED' AND p_failure_reason IS NULL THEN
        RAISE EXCEPTION 'failure_reason is required when marking a node FAILED';
    END IF;

    UPDATE execution_nodes
    SET status         = p_status,
        failure_reason = CASE WHEN p_status = 'FAILED' THEN p_failure_reason ELSE failure_reason END,
        completed_at   = now(),
        updated_at     = now()
    WHERE organization_id      = p_organization_id
      AND workflow_instance_id = p_workflow_instance_id
      AND ref_id               = p_ref_id
      AND ref_type             = p_ref_type
      AND status IN ('PENDING', 'RUNNING');   -- never re-complete a terminal node

    GET DIAGNOSTICS v_updated = ROW_COUNT;
    RETURN v_updated;
END;
$$;


-- ============================================================
-- 3. Read model
-- ============================================================

-- 3a. Flattened graph with depth, for rendering a workflow as a tree.
-- Recursive CTE walks down from the roots (parent_node_id IS NULL).
CREATE OR REPLACE VIEW smm.execution_graph AS
WITH RECURSIVE tree AS (
    SELECT
        n.id,
        n.organization_id,
        n.workflow_instance_id,
        n.parent_node_id,
        n.node_type,
        n.status,
        n.display_name,
        n.ref_id,
        n.ref_type,
        n.failure_reason,
        n.created_at,
        n.completed_at,
        0                       AS depth,
        ARRAY[n.created_at]     AS sort_path
    FROM execution_nodes n
    WHERE n.parent_node_id IS NULL

    UNION ALL

    SELECT
        c.id,
        c.organization_id,
        c.workflow_instance_id,
        c.parent_node_id,
        c.node_type,
        c.status,
        c.display_name,
        c.ref_id,
        c.ref_type,
        c.failure_reason,
        c.created_at,
        c.completed_at,
        t.depth + 1,
        t.sort_path || c.created_at
    FROM execution_nodes c
    JOIN tree t
      ON c.parent_node_id  = t.id
     -- A child must never cross tenants or workflows, even if a bad write
     -- created one; joining on all three keeps the view from leaking it.
     AND c.organization_id = t.organization_id
     AND c.workflow_instance_id = t.workflow_instance_id
)
SELECT * FROM tree;

-- Callers must still filter: SELECT * FROM smm.execution_graph
--   WHERE organization_id = :organization_id AND workflow_instance_id = :wf
--   ORDER BY sort_path;


-- 3b. One row per workflow instance: rollup status + counts.
CREATE OR REPLACE VIEW smm.workflow_instance_summary AS
SELECT
    n.organization_id,
    n.workflow_instance_id,
    max(n.display_name) FILTER (WHERE n.parent_node_id IS NULL) AS root_name,
    max(n.ref_id::text) FILTER (WHERE n.parent_node_id IS NULL) AS root_ref_id,
    count(*)                                                    AS node_count,
    count(*) FILTER (WHERE n.status = 'PENDING')                AS pending_count,
    count(*) FILTER (WHERE n.status = 'RUNNING')                AS running_count,
    count(*) FILTER (WHERE n.status = 'SUCCEEDED')              AS succeeded_count,
    count(*) FILTER (WHERE n.status = 'FAILED')                 AS failed_count,
    count(*) FILTER (WHERE n.status = 'CANCELLED')              AS cancelled_count,
    CASE
        WHEN count(*) FILTER (WHERE n.status = 'FAILED')  > 0 THEN 'FAILED'
        WHEN count(*) FILTER (WHERE n.status = 'RUNNING') > 0 THEN 'RUNNING'
        WHEN count(*) FILTER (WHERE n.status IN ('PENDING', 'RUNNING')) = 0 THEN 'SUCCEEDED'
        ELSE 'PENDING'
    END                                                         AS rollup_status,
    min(n.created_at)                                           AS started_at,
    max(n.completed_at) FILTER (
        WHERE n.status IN ('SUCCEEDED', 'FAILED', 'CANCELLED')
    )                                                           AS last_completed_at
FROM execution_nodes n
GROUP BY n.organization_id, n.workflow_instance_id;


-- ============================================================
-- 4. Operational queries
-- ============================================================

-- 4a. In-flight work for one tenant, oldest first — the recovery query.
-- "No in-memory session state" means a cold start must be able to rebuild
-- what is outstanding from this alone. Uses ix_execution_nodes_org_open.
SELECT
    n.workflow_instance_id,
    n.id AS node_id,
    n.node_type,
    n.status,
    n.display_name,
    n.ref_type,
    n.ref_id,
    n.created_at,
    now() - n.created_at AS age
FROM execution_nodes n
WHERE n.organization_id = :organization_id
  AND n.status IN ('PENDING', 'RUNNING')
ORDER BY n.created_at
LIMIT 500;


-- 4b. Stuck nodes — in flight past their SLA. Feed this to alerting.
SELECT
    n.organization_id,
    n.workflow_instance_id,
    n.id AS node_id,
    n.node_type,
    n.status,
    n.created_at,
    now() - n.created_at AS stuck_for
FROM execution_nodes n
WHERE n.status IN ('PENDING', 'RUNNING')
  AND n.created_at < now() - (:stuck_after_minutes || ' minutes')::interval
ORDER BY n.created_at;


-- 4c. Graph node joined to the domain row it references, for one campaign.
-- Replaces a 6-way LEFT JOIN: only one branch of the CASE is ever non-null
-- per row, so resolving the label per ref_type keeps the plan flat.
SELECT
    n.workflow_instance_id,
    n.node_type,
    n.status,
    n.ref_type,
    n.ref_id,
    CASE n.ref_type
        WHEN 'CAMPAIGN'    THEN (SELECT c.name        FROM campaigns    c WHERE c.id = n.ref_id AND c.organization_id = n.organization_id)
        WHEN 'POST'        THEN (SELECT left(p.caption, 80) FROM posts  p WHERE p.id = n.ref_id AND p.organization_id = n.organization_id)
        WHEN 'APPROVAL'    THEN (SELECT a.stage::text  FROM approvals   a WHERE a.id = n.ref_id AND a.organization_id = n.organization_id)
        WHEN 'PUBLISH_JOB' THEN (SELECT j.status::text FROM publish_jobs j WHERE j.id = n.ref_id AND j.organization_id = n.organization_id)
        ELSE NULL
    END AS ref_label,
    n.failure_reason,
    n.created_at,
    n.completed_at
FROM execution_nodes n
WHERE n.organization_id      = :organization_id
  AND n.workflow_instance_id = :workflow_instance_id
ORDER BY n.created_at;


-- 4d. Orphan check — posts with no execution node. Should return zero rows
-- once workflow creation is wired into the campaign/post creation flow;
-- non-zero means the bridge created domain rows without a graph.
SELECT p.id AS post_id, p.campaign_id, p.status, p.created_at
FROM posts p
WHERE p.organization_id = :organization_id
  AND NOT EXISTS (
      SELECT 1 FROM execution_nodes n
      WHERE n.organization_id = p.organization_id
        AND n.ref_type        = 'POST'
        AND n.ref_id          = p.id
  )
ORDER BY p.created_at DESC;


-- ============================================================
-- DRIFT FROM smm_gtm_bridge.sql SECTION 3
-- ============================================================
-- Each of these makes the older DDL/statements fail or misbehave against
-- the ExecutionNode model as written:
--
-- 1. Enum labels. Old file uses lowercase text ('pending', 'campaign') with
--    CHECK constraints. The model declares native PG enums, and SQLAlchemy
--    persists member NAMES, so the real labels are uppercase. This also
--    breaks an existing index in that file's section 5:
--        ix_publish_jobs_status_next ... WHERE status IN ('queued','retrying')
--    publish_job_status has labels QUEUED/RETRYING, so that predicate matches
--    nothing and the partial index is dead. Worth fixing there too.
--
-- 2. Missing updated_at. TimestampMixin makes it NOT NULL with no server
--    default. Every INSERT in the old section 3 omits it -> not-null violation.
--
-- 3. gen_random_uuid() as the id default. base.py states the server-side
--    default is deliberately not used, for SQLite parity. Keeping the old
--    default would let raw SQL insert rows the ORM path cannot reproduce.
--
-- 4. Missing display_name. Present on the model and populated by
--    WorkflowService.create_workflow_instance; absent from the old DDL.
--
-- 5. No FK on parent_node_id. The model declares
--    ForeignKey("execution_nodes.id", ondelete="SET NULL").
--
-- 6. Duplicate org index. Old file adds ix_execution_nodes_org while
--    OrgScopedMixin's index=True already yields
--    ix_execution_nodes_organization_id.
--
-- 7. No tenant predicate on the completion UPDATEs (old 3c), and no
--    idempotence guard on the child INSERTs (old 3b).
