"""Media router: presigned upload URLs + register + list + get/delete assets.

Actual binary upload happens client-side against a pre-signed S3/MinIO URL
generated by ``POST /api/v1/media/upload-url``. Once the client finishes the
upload it calls ``POST /api/v1/media/confirm`` to persist the metadata row
in Postgres.

The existing ``POST /api/v1/media`` endpoint is kept for direct registration
flows.
"""
from __future__ import annotations

import uuid
from datetime import timedelta

import boto3
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.auth import get_current_org
from app.core.config import get_settings
from app.core.db import get_db
from app.core.exceptions import NotFoundError
from app.models.media import Media
from app.repositories.media_repository import MediaRepository
from app.schemas.common import Page
from app.schemas.media import MediaCreate, MediaRead

router = APIRouter(prefix="/api/v1/media", tags=["media"])


def _get_s3_client() -> boto3.client:
    """Return a boto3 S3 client configured from :class:`Settings`.

    Uses boto3 resolution order so tests can override with
    ``AWS_*`` environment variables when appropriate.
    """
    settings = get_settings()
    return boto3.client(
        "s3",
        endpoint_url=settings.S3_ENDPOINT_URL,
        region_name=settings.S3_REGION,
        aws_access_key_id=settings.S3_ACCESS_KEY_ID,
        aws_secret_access_key=settings.S3_SECRET_ACCESS_KEY,
        use_ssl=settings.S3_USE_SSL,
    )


@router.post("/upload-url", status_code=status.HTTP_200_OK)
async def generate_upload_url(
    filename: str = Query(min_length=1, max_length=255),
    content_type: str = Query(min_length=1, max_length=255),
    org_id: str = Depends(get_current_org),
) -> dict:
    """Return a pre-signed PUT URL the client can use to upload a media file
    directly to MinIO/S3 without touching our API further for the binary.

    Parameters
    ----------
    filename:
        Client-side filename used to derive the storage key.
    content_type:
        Expected ``Content-Type`` header value; the pre-signed URL is issued
        with a matching condition so only the intended content type is allowed.
    """
    settings = get_settings()
    storage_key = f"{org_id}/{uuid.uuid4().hex}-{filename}"

    s3 = _get_s3_client()
    expires_in = int(timedelta(minutes=15).total_seconds())
    try:
        presigned = s3.generate_presigned_url(
            client_method="put_object",
            Params={
                "Bucket": settings.S3_BUCKET_NAME,
                "Key": storage_key,
                "ContentType": content_type,
            },
            ExpiresIn=expires_in,
        )
    except Exception as exc:  # pragma: no cover - defensive
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to generate upload URL: {exc}",
        ) from exc

    return {
        "upload_url": presigned,
        "storage_key": storage_key,
        "public_url": f"{settings.S3_PUBLIC_URL_BASE.rstrip('/')}/{storage_key}",
        "expires_in": expires_in,
        "content_type": content_type,
    }


@router.post("/confirm", response_model=MediaRead, status_code=status.HTTP_201_CREATED)
async def confirm_upload(
    payload: MediaCreate,
    org_id: str = Depends(get_current_org),
    db: AsyncSession = Depends(get_db),
) -> Media:
    """Persist a ``Media`` metadata row after the client has finished uploading
    the binary object to the pre-signed URL.

    The client must pass the same fields that the legacy ``POST /`` endpoint
    accepted: the bucket-relative ``storage_key`` plus metadata describing the
    asset.
    """
    repo = MediaRepository(db)
    media = Media(organization_id=uuid.UUID(org_id), **payload.model_dump())
    media = await repo.create(media)
    await db.commit()
    await db.refresh(media)
    return media


@router.post("", response_model=MediaRead, status_code=status.HTTP_201_CREATED)
async def register_media(
    payload: MediaCreate,
    org_id: str = Depends(get_current_org),
    db: AsyncSession = Depends(get_db),
) -> Media:
    """Register a media asset that has already been uploaded to object storage."""
    repo = MediaRepository(db)
    media = Media(organization_id=uuid.UUID(org_id), **payload.model_dump())
    media = await repo.create(media)
    await db.commit()
    await db.refresh(media)
    return media


@router.get("", response_model=Page[MediaRead])
async def list_media(
    page: int = Query(default=1, ge=1),
    page_size: int = Query(default=20, ge=1, le=200),
    post_id: uuid.UUID | None = Query(default=None),
    org_id: str = Depends(get_current_org),
    db: AsyncSession = Depends(get_db),
) -> Page[MediaRead]:
    """List media assets, optionally filtered by post."""
    repo = MediaRepository(db)
    extra_filters = [Media.post_id == post_id] if post_id else None
    result = await repo.list_paginated(
        uuid.UUID(org_id), page=page, page_size=page_size, extra_filters=extra_filters
    )
    return Page[MediaRead](
        items=[MediaRead.model_validate(m) for m in result.items],
        total=result.total,
        page=result.page,
        page_size=result.page_size,
        total_pages=result.total_pages,
    )


@router.get("/{media_id}", response_model=MediaRead)
async def get_media(
    media_id: uuid.UUID,
    org_id: str = Depends(get_current_org),
    db: AsyncSession = Depends(get_db),
) -> Media:
    """Fetch a single media asset by id."""
    repo = MediaRepository(db)
    media = await repo.get_by_id(uuid.UUID(org_id), media_id)
    if media is None:
        raise NotFoundError(f"Media {media_id} not found.")
    return media


@router.delete(
    "/{media_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_model=None,
)
async def delete_media(
    media_id: uuid.UUID,
    org_id: str = Depends(get_current_org),
    db: AsyncSession = Depends(get_db),
) -> None:
    """Delete a media asset's metadata row (does not delete the S3 object —
    that is handled by a lifecycle policy / separate cleanup job)."""
    repo = MediaRepository(db)
    media = await repo.get_by_id(uuid.UUID(org_id), media_id)
    if media is None:
        raise NotFoundError(f"Media {media_id} not found.")
    await repo.delete(media)
    await db.commit()
