"""add integration_mounts

Revision ID: 11bbfaf5a443
Revises: 412a32e37eb2
Create Date: 2026-07-24 18:44:49.279352

Hand edits to the autogenerated output (both are documented gotchas in
.claude/agents/smm-backend.md):

1. Added ``import app.core.db_types`` — autogenerate renders
   ``app.core.db_types.GUID()`` / ``StringArrayCompat()`` but never emits the
   import, so the unedited file raises NameError on upgrade.
2. Dropped the spurious ``drop_index``/``create_index`` pair autogenerate
   emitted for ``ix_execution_nodes_org_open`` and
   ``ix_execution_nodes_org_workflow_ref``. Those are hand-written composite/
   partial indexes added in 412a32e37eb2; they do not exist in
   ``Base.metadata``, so every subsequent autogenerate believes they were
   removed. Applying that diff would silently delete them.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = '11bbfaf5a443'
down_revision: Union[str, None] = '412a32e37eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_mounts',
    sa.Column('external_system', sa.String(length=100), nullable=False),
    sa.Column('external_tenant_id', sa.String(length=255), nullable=False),
    sa.Column('platforms', app.core.db_types.StringArrayCompat(), nullable=True),
    sa.Column('default_brand_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'external_system', 'external_tenant_id', name='uq_integration_mount_org_system_tenant')
    )
    with op.batch_alter_table('integration_mounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_mounts_default_brand_id'), ['default_brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_mounts_external_system'), ['external_system'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_mounts_external_tenant_id'), ['external_tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_mounts_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_mounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_mounts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_integration_mounts_external_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integration_mounts_external_system'))
        batch_op.drop_index(batch_op.f('ix_integration_mounts_default_brand_id'))

    op.drop_table('integration_mounts')
    # ### end Alembic commands ###
