"""add execution_nodes

Revision ID: 412a32e37eb2
Revises: a1b4bb27ec5c
Create Date: 2026-07-24 18:22:03.919402

NOTE on the two composite indexes at the end of upgrade() (ix_execution_nodes_org_workflow_ref,
ix_execution_nodes_org_open): these are hand-added, not declared as index=True columns on
ExecutionNode. A future `alembic revision --autogenerate` will therefore propose a migration
that DROPS them (autogenerate diffs the DB against ORM metadata, which knows nothing about
these two). That proposal should be discarded/edited out when it appears -- it is not real
drift, just a known gap between this migration and what the model declares. Decided
2026-07-24 to accept this rather than add an include_object filter to alembic/env.py.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = '412a32e37eb2'
down_revision: Union[str, None] = 'a1b4bb27ec5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_nodes',
    sa.Column('workflow_instance_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('parent_node_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('node_type', sa.Enum('INTAKE', 'CAMPAIGN', 'POST', 'PUBLISH_JOB', 'APPROVAL', 'INTEGRATION_EVENT', name='workflow_node_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='workflow_node_status'), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('ref_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('ref_type', sa.Enum('CAMPAIGN', 'POST', 'SCHEDULE', 'PUBLISH_JOB', 'APPROVAL', 'AUDIT_LOG', name='execution_node_ref_type'), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['execution_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_nodes_node_type'), ['node_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_parent_node_id'), ['parent_node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_ref_type'), ['ref_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_nodes_workflow_instance_id'), ['workflow_instance_id'], unique=False)

    # ### end Alembic commands ###

    # --- hand-added: hot-path composites, not emitted by autogenerate ---
    # See docs/sql/execution_nodes.sql section 1 for the rationale on each.
    op.create_index(
        'ix_execution_nodes_org_workflow_ref',
        'execution_nodes',
        ['organization_id', 'workflow_instance_id', 'ref_type', 'ref_id'],
    )
    op.create_index(
        'ix_execution_nodes_org_open',
        'execution_nodes',
        ['organization_id', 'created_at'],
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
        sqlite_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_nodes_org_open', table_name='execution_nodes')
    op.drop_index('ix_execution_nodes_org_workflow_ref', table_name='execution_nodes')
    with op.batch_alter_table('execution_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_nodes_workflow_instance_id'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_status'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_ref_type'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_ref_id'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_parent_node_id'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_execution_nodes_node_type'))

    op.drop_table('execution_nodes')
    # ### end Alembic commands ###
