"""initial schema

Revision ID: 92ba5d1cd517
Revises: 
Create Date: 2026-07-20 03:00:23.623939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = '92ba5d1cd517'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_clerk_org_id'), ['clerk_org_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_clerk_user_id'), ['clerk_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('ai_requests',
    sa.Column('requested_by_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('metadata_json', app.core.db_types.JSONBCompat(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_requests_operation'), ['operation'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_requests_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STATE_TRANSITION', 'LOGIN', 'PUBLISH', 'OTHER', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('metadata_json', app.core.db_types.JSONBCompat(), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=1024), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.String(length=4000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)

    op.create_table('notifications',
    sa.Column('recipient_user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('APPROVAL_REQUESTED', 'APPROVAL_RECEIVED', 'POST_PUBLISHED', 'POST_FAILED', 'COMMENT_ADDED', 'TASK_ASSIGNED', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=1024), nullable=True),
    sa.Column('metadata_json', app.core.db_types.JSONBCompat(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    op.create_table('organization_memberships',
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'CLIENT_VIEWER', name='org_role'), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_membership_org_user')
    )
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('prompt_templates',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('variables', app.core.db_types.StringArrayCompat(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', 'version', name='uq_prompt_template_org_slug_version')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_templates_slug'), ['slug'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)

    op.create_table('brands',
    sa.Column('client_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voice', sa.String(length=2000), nullable=True),
    sa.Column('audience', sa.String(length=2000), nullable=True),
    sa.Column('keywords', app.core.db_types.StringArrayCompat(), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('brand_colors', app.core.db_types.JSONBCompat(), nullable=True),
    sa.Column('guidelines', sa.String(length=8000), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_brands_organization_id'), ['organization_id'], unique=False)

    op.create_table('team_memberships',
    sa.Column('team_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('user_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_membership_team_user')
    )
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_memberships_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('client_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('brand_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaign_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_status'), ['status'], unique=False)

    op.create_table('platform_accounts',
    sa.Column('brand_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('platform', sa.Enum('LINKEDIN', 'FACEBOOK', 'INSTAGRAM', 'X', 'THREADS', 'TIKTOK', 'PINTEREST', 'YOUTUBE', 'GOOGLE_BUSINESS', name='platform_name'), nullable=False),
    sa.Column('external_account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=4000), nullable=True),
    sa.Column('refresh_token', sa.String(length=4000), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_accounts_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_accounts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_accounts_platform'), ['platform'], unique=False)

    op.create_table('posts',
    sa.Column('campaign_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_by_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_type', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', app.core.db_types.StringArrayCompat(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'REJECTED', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='post_status'), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    op.create_table('tasks',
    sa.Column('campaign_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('assignee_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_user_id'), ['assignee_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('analytics',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('raw_payload', app.core.db_types.JSONBCompat(), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_post_id'), ['post_id'], unique=False)

    op.create_table('approvals',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('reviewer_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='approval_status'), nullable=False),
    sa.Column('feedback', sa.String(length=4000), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_reviewer_user_id'), ['reviewer_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('author_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('parent_comment_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_comment_id'), ['parent_comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('media',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'GIF', 'DOCUMENT', name='media_type'), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=1000), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_post_id'), ['post_id'], unique=False)

    op.create_table('post_versions',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('hashtags', app.core.db_types.StringArrayCompat(), nullable=True),
    sa.Column('edited_by_user_id', app.core.db_types.GUID(), nullable=True),
    sa.Column('change_summary', sa.String(length=1000), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'version_number', name='uq_post_version_number')
    )
    with op.batch_alter_table('post_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_versions_post_id'), ['post_id'], unique=False)

    op.create_table('publish_jobs',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('platform_account_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'RETRYING', 'CANCELLED', name='publish_job_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_jobs_platform_account_id'), ['platform_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_jobs_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publish_jobs_status'), ['status'], unique=False)

    op.create_table('schedules',
    sa.Column('post_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('platform_account_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', app.core.db_types.GUID(), nullable=False),
    sa.Column('organization_id', app.core.db_types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_platform_account_id'), ['platform_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedules_scheduled_at'), ['scheduled_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_schedules_post_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_platform_account_id'))
        batch_op.drop_index(batch_op.f('ix_schedules_organization_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_publish_jobs_post_id'))
        batch_op.drop_index(batch_op.f('ix_publish_jobs_platform_account_id'))
        batch_op.drop_index(batch_op.f('ix_publish_jobs_organization_id'))

    op.drop_table('publish_jobs')
    with op.batch_alter_table('post_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_versions_post_id'))

    op.drop_table('post_versions')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_post_id'))
        batch_op.drop_index(batch_op.f('ix_media_organization_id'))

    op.drop_table('media')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_parent_comment_id'))
        batch_op.drop_index(batch_op.f('ix_comments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_comments_author_user_id'))

    op.drop_table('comments')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_post_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_organization_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_post_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_organization_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_captured_at'))

    op.drop_table('analytics')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_campaign_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_user_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))
        batch_op.drop_index(batch_op.f('ix_posts_platform'))
        batch_op.drop_index(batch_op.f('ix_posts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_posts_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_posts_campaign_id'))

    op.drop_table('posts')
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_platform_accounts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_platform_accounts_brand_id'))

    op.drop_table('platform_accounts')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_status'))
        batch_op.drop_index(batch_op.f('ix_campaigns_organization_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_name'))
        batch_op.drop_index(batch_op.f('ix_campaigns_client_id'))
        batch_op.drop_index(batch_op.f('ix_campaigns_brand_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_memberships_team_id'))

    op.drop_table('team_memberships')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_organization_id'))
        batch_op.drop_index(batch_op.f('ix_brands_client_id'))

    op.drop_table('brands')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_slug'))
        batch_op.drop_index(batch_op.f('ix_prompt_templates_organization_id'))

    op.drop_table('prompt_templates')
    with op.batch_alter_table('organization_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_memberships_organization_id'))

    op.drop_table('organization_memberships')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clients_name'))

    op.drop_table('clients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_requests_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ai_requests_operation'))

    op.drop_table('ai_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_clerk_user_id'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_clerk_org_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
